name: files
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  device_apps:
    git: https://github.com/faisalansari0367/flutter_plugin_device_apps-master.git
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  mime_type: ^1.0.0
  open_file: ^3.0.3
  percent_indicator: ^3.0.1
  # permission_handler: 7.2.0
  permission_handler: ^8.2.5
  provider: ^5.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  storage_details: ^0.0.3
  storage_path: ^0.2.0
  video_thumbnail: ^0.4.3
  google_sign_in: ^5.1.0
  googleapis: ^5.0.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  http: ^0.13.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.2
  bezier_chart: ^1.0.17+1
  fl_chart: ^0.36.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cached_network_image: ^3.1.0+1
  ext_storage: ^1.0.3
  # shimmer_animation: ^2.1.0+1
  shimmer: ^2.0.0
  tuple: ^2.0.0
  wallpaper_manager_flutter: ^0.0.2
  transformer_page_view: ^0.1.6
  extended_image: ^5.1.3
  # wallpaper_manager: ^1.0.10
  # intl: ^0.16.1

dependency_overrides:
  # firebase_auth: ^3.1.1
  # bezier_chart: ^1.0.17+1
  intl: ^0.16.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.1
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
  test: 
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

# run this command after changing icon flutter pub run flutter_native_splash:create
flutter_native_splash:
  # color: "#ffffff"
  image: assets/icon/app_icon.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/onboard/
    - assets/icon/

    # - assets/icon/icon.png
    # - assets/empty.png
    # - assets/empty2.png
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
